dev
TechsophyOfficial/awgment-app-runtime-form pull request #28
Opened 2023-02-02 08:37 UTC by denduluriramasaimohanakhil

coverage:85%
 lint:53
RemovingLint:
 coverage:85%
 lint:0

2023-02-03 04:35 UTC, VaibhavTechsophy requested changes
Need to fix duplicate code, and some parts seem overly complex please discuss with me

2023-02-03 04:35 UTC, VaibhavTechsophy commented on src/main/java/com/techsophy/tsf/runtime/form/service/impl/FormDataServiceImpl.java
> +                    checkDocumentFlag(documentFlag, uniqueDocumentId);
what is the check for?

2023-02-03 04:35 UTC, VaibhavTechsophy commented on src/main/java/com/techsophy/tsf/runtime/form/service/impl/FormDataServiceImpl.java
>          Integer version = null;
Need to understand what this code is doing, please explain, it looks unnecessarily complex

2023-02-07 05:31 UTC, denduluriramasaimohanakhil commented
Vaibhav can u please merge now all sonar checks have passed and code coverage is at 85% and sonar lint issues reduced to ZERO

2023-02-07 06:26 UTC, VaibhavTechsophy approved these changes

2023-02-07 06:26 UTC, VaibhavTechsophy commented on src/main/java/com/techsophy/tsf/runtime/form/service/impl/SequenceGeneratorServiceImpl.java
> +        sequenceGeneratorDefinition.setUpdatedOn(String.valueOf(Date.from(Instant.now())));
what is the issue here?

2023-02-07 06:27 UTC, merged