ACL Check in formData Controller
TechsophyOfficial/awgment-app-runtime-form pull request #37
Opened 2023-02-27 09:57 UTC by denduluriramasaimohanakhil

lint: 0
   coverage :85%
ACLControllerCheck:
   lint :0
   coverage :85%

2023-02-27 11:32 UTC, VaibhavTechsophy requested changes

2023-02-27 11:32 UTC, VaibhavTechsophy commented on src/main/java/com/techsophy/tsf/runtime/form/controller/impl/FormDataControllerImpl.java
> +            if(aclEvaluator.getRead(tokenUtils.getTokenFromContext()).getDecision().equals(DENY))
what about undefined?

2023-02-27 11:32 UTC, VaibhavTechsophy commented on src/main/java/com/techsophy/tsf/runtime/form/controller/impl/FormDataControllerImpl.java
> +            if(aclEvaluator.getRead(tokenUtils.getTokenFromContext()).getDecision().equals(DENY))
in all below instances also, can we keep the code reusable

2023-02-27 11:32 UTC, VaibhavTechsophy commented on src/main/java/com/techsophy/tsf/runtime/form/controller/impl/FormDataControllerImpl.java
> +            if(aclEvaluator.getRead(tokenUtils.getTokenFromContext()).getDecision().equals(DENY))
can u write a function like checkACL(formId, relations, rules)
With rules being read/update/delete.

2023-02-27 14:11 UTC, denduluriramasaimohanakhil commented on src/main/java/com/techsophy/tsf/runtime/form/controller/impl/FormDataControllerImpl.java
> +            if(aclEvaluator.getRead(tokenUtils.getTokenFromContext()).getDecision().equals(DENY))
Implemented as mentioned above

2023-02-28 02:35 UTC, VaibhavTechsophy commented on src/main/java/com/techsophy/tsf/runtime/form/controller/impl/FormDataControllerImpl.java
> +            assert decision != null;
good

2023-02-28 02:35 UTC, VaibhavTechsophy approved these changes

2023-02-28 02:35 UTC, merged