Audit formdata version fix
TechsophyOfficial/awgment-app-runtime-form pull request #95
Opened 2023-07-20 07:18 UTC by bhavya-alla

2023-07-20 08:13 UTC, VaibhavTechsophy requested changes

2023-07-20 08:13 UTC, VaibhavTechsophy commented on src/test/java/com/techsophy/tsf/runtime/form/service/impl/FormDataServiceImplTest.java
> +  void updateFormDataTestToSaveToAudit() throws JsonProcessingException {
Please add a positive test case and verify that the version is getting set properly by capturing arguments sent to downstream.

2023-07-20 12:45 UTC, VaibhavTechsophy requested changes, later dismissed

2023-07-20 12:45 UTC, VaibhavTechsophy commented on src/main/java/com/techsophy/tsf/runtime/form/service/impl/FormDataServiceImpl.java
> +  @Value(DEFAULT_PAGE_LIMIT)
Please make a proper commit so that changes are highlighted for review.

2023-07-20 12:45 UTC, VaibhavTechsophy commented on src/test/java/com/techsophy/tsf/runtime/form/service/impl/FormDataServiceImplTest.java
> +    when(formDataAuditService.saveFormDataAudit(any())).thenReturn(formDataAuditResponse);
Instead of mocking the response, capture the input to this call and verify the value.

2023-07-20 12:45 UTC, VaibhavTechsophy commented on src/test/java/com/techsophy/tsf/runtime/form/service/impl/FormDataServiceImplTest.java
> +    Assertions.assertEquals(Integer.valueOf(formDataDefinition.getVersion()),formDataAuditResponse.getVersion());
This is not useful to verify the response returned from mock

2023-07-20 12:45 UTC, VaibhavTechsophy commented on src/test/java/com/techsophy/tsf/runtime/form/service/impl/FormDataServiceImplTest.java
> +    when(formDataAuditService.saveFormDataAudit(any())).thenReturn(formDataAuditResponse);
same issue as above.

2023-07-31 06:58 UTC, SanjaySinghTechsophy approved these changes

2023-07-31 06:59 UTC, merged